# Generated by Django 6.1.1 on 2026-09-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=200)),
                ('simu', models.CharField(blank=True, max_length=20)),
                ('eneo', models.CharField(blank=True, max_length=150)),
                ('kiasi_anachotakiwa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarehe_ya_usajili', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('Mixx by Yas', 'Mixx by Yas'), ('Halopesa', 'Halopesa'), ('Benki', 'Benki'), ('Nyingine', 'Nyingine')], max_length=50)),
                ('transaction_number', models.CharField(blank=True, max_length=100)),
                ('tarehe', models.DateTimeField(auto_now_add=True)),
                ('maelezo', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.member')),
            ],
        ),
    ]
