# Generated by Django 6.1.1 on 2026-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tarehe_ya_mwisho',
            field=models.DateField(blank=True, null=True),
        ),
    ]
