# Generated by Django 6.1.1 on 2026-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_member_active_member_tarehe_ya_mwisho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('Mixx by Yas', 'Mixx by Yas'), ('Halopesa', 'Halopesa'), ('Benki', 'Benki'), ('Nyingine', 'Nyingine')], default='Cash', max_length=50),
        ),
    ]
